name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CGO_ENABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: go build -tags "unit" ./...

    - name: Test
      run: go test -race ./... -tags unit -v
      
